### ISSUE TITLE
java8 Can't it be used???

### ISSUE THREAD

**Issue by ferrymo** [ks-shim/JImageHash-Light#1]
run Exception :
```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/scene/image/Image
	at io.github.ksshim.jimagehash.hashAlgorithms.HashingAlgorithm.createPixelAccessor(HashingAlgorithm.java:296)
	at io.github.ksshim.jimagehash.hashAlgorithms.PerceptiveHash.hash(PerceptiveHash.java:70)
	at io.github.ksshim.jimagehash.hashAlgorithms.HashingAlgorithm.hash(HashingAlgorithm.java:250)
	at io.github.ksshim.jimagehash.hashAlgorithms.HashingAlgorithm.hash(HashingAlgorithm.java:271) 
```

**Comment by ferrymo** [comment]
I used the wrong JDK version, currently using version 181, everything is normal
